return {
	{ number = "customCatalog-1", album = { "Abdulrahman Alsudaes Musshaf", "http://www.assabile.com/" }, artist = { "Abdulrahman Alsudaes", "Abdul Rahman Al Sudais" } },
	{ number = "SVWC-70166~7", album = { "デュラララッピング!! -「デュラララ!!」BEST-", "DRRR Wrapping!! -DuRaRaRa!! BEST-" }, artist = { "THEATRE BROOK", "Matsushita Yuya", "Yuya Matsushita", "ROOKiEZ is PUNK'D", "ON/OFF", "OKAMOTO’S", "THREE LIGHTS DOWN KINGS", "Toyonaga Toshiyuki", "Toshiyuki Toyonaga", "REVALCY", "FLOW", "PENGUIN RESEARCH" } },
	{ number = "SVWC-70149", album = { "甲鉄城のカバネリ オリジナル・サウンドトラック", "Koutetsujou no Kabaneri ORIGINAL SOUNDTRACK" }, artist = { "Eliana", "mpi", "Sawano Hiroyuki", "Hiroyuki Sawano", "Kobayashi Mika", "Mika Kobayashi", "Benjamin", "Cyua" } },
	{ number = "KSLA-0143", album = { "Rita×Key Memorial Best 『streak of light』" }, artist = { "Rita", "Minoru Yoshida", "Yoshida Minoru", "Atsushi Hasegawa", "Hasegawa Atsushi", "TAKUYA", "Tomonori Kimura", "Kimura Tomonori", "HAZE", "Shoyu", "Tatuki Harada", "Harada Tatuki" } },
	-- Haru Nemuri
	{ number = "DISCB-3710", album = { "アトム・ハート・マザー", "Atom Heart Mother" }, artist = { "春ねむり", "Haru Nemuri", "Nemuri Haru" } },
	{ number = "PMFL-0008", album = { "春と修羅", "Haru to Shura" }, artist = { "春ねむり", "Haru Nemuri", "Nemuri Haru" } },
	-- Lamb of God
	{ number = "3984-14345-2", album = { "New American Gospel" }, artist = { "Lamb of God" } },
	{ number = "10008-2", album = { "As the Palaces Burn"}, artist = { "Lamb of God" } },
	{ number = "517933 2", album = { "Ashes of the Wake"}, artist = { "Lamb of God" } },
	{ number = "82876 87343 2", album = { "Sacrament" }, artist = { "Lamb of God" } },
	{ number = "RRCY-21335", album = { "Wrath", "Wrath (Limited Edition)" }, artist = { "Lamb of God" } },
	{ number = "RR 7655-5", album = { "Resolution" }, artist = { "Lamb of God" } },
	{ number = "NB 3559-0", album = { "VII: Sturm und Drang", "Sturm und Drang" }, artist = { "Lamb of God" } },
	-- ONE OK ROCK
	{ number = "AZCL-10011", album = { "ゼイタクビョウ", "Zeitakubyō", "Zeitakubyo", "Zeitakubyou" }, artist = { "ONE OK ROCK" } },
	{ number = "AZCL-10017", album = { "BEAM OF LIGHT", "Beam of Light" }, artist = { "ONE OK ROCK" } },
	{ number = "AZCB-1001", album = { "感情エフェクト", "Kanjō Effect", "Kanjo Effect" }, artist = { "ONE OK ROCK" } },
	{ number = "AZCS-1005", album = { "Nicheシンドローム", "Niche Syndrome", "NICHE シンドローム" }, artist = { "ONE OK ROCK" } },
	{ number = "AZCS-1016", album = { "残響リファレンス", "Zankyō Reference", "Zankyo Reference", "Zankyō Rifarensu", "Zankyo Rifarensu" }, artist = { "ONE OK ROCK" } },
	{ number = "AZCS-1024", album = { "人生×僕=", "Jinsei×Boku=", "Jinsei × Boku =", "Jinsei Kakete Boku wa" }, artist = { "ONE OK ROCK" } },
	{ number = "AZCS-1041", album = { "35xxxv" }, artist = { "ONE OK ROCK" } },
	{ number = "551401-2", album = { "35xxxv (Deluxe Edition)" }, artist = { "ONE OK ROCK" } },
	{ number = "AZCS-1062", album = { "Ambitions", "Ambitions (Japanese version)" }, artist = { "ONE OK ROCK" } },
	{ number = "558469-2", album = { "Ambitions (English version)", "Ambitions (International version)", "Ambitions (English ver.)", "Ambitions (International ver.)" }, artist = { "ONE OK ROCK" } },
	-- DragonForce
	{ number = "82310-74084-2", album = { "Valley of the Damned" }, artist = { "DragonForce" } },
	{ number = "82310-74142-2", album = { "Sonic Firestorm" }, artist = { "DragonForce" } },
	{ number = "168 618 034-2", album = { "Inhuman Rampage" }, artist = { "DragonForce" } },
	{ number = "0602517787797", album = { "Ultra Beatdown" }, artist = { "DragonForce" } },
	{ number = "EG5754", album = { "The Power Within" }, artist = { "DragonForce" } },
	{ number = "SR1062", album = { "Maximum Overload" }, artist = { "DragonForce" } },
	{ number = "WPCR-17718", album = { "Reaching Into Infinity" }, artist = { "DragonForce" } },
	-- Linkin Park
	{ number = "9 47755-2", album = { "Hybrid Theory" }, artist = { "Linkin Park" } },
	{ number = "9362 48444 2", album = { "Meteora" }, artist = { "Linkin Park" } },
	{ number = "44477-2", album = { "Minutes to Midnight" }, artist = { "Linkin Park" } },
	{ number = "525375-2", album = { "A Thousand Suns" }, artist = { "Linkin Park" } },
	{ number = "531345-2", album = { "Living Things" }, artist = { "Linkin Park" } },
	{ number = "543028-2", album = { "The Hunting Party" }, artist = { "Linkin Park" } },
	{ number = "559687-2", album = { "One More Light" }, artist = { "Linkin Park" } },
	-- Dream Theater
	{ number = "MCAD42259", album = { "When Dream and Day Unite" }, artist = { "Dream Theater" } },
	{ number = "7567-92148-2", album = { "Images and Words" }, artist = { "Dream Theater" } },
	{ number = "7567-90126-2", album = { "Awake" }, artist = { "Dream Theater" } },
	{ number = "7559-62060-2", album = { "Falling Into Infinity" }, artist = { "Dream Theater" } },
	{ number = "7559-62448-2", album = { "Metropolis, Pt. 2: Scenes From a Memory" }, artist = { "Dream Theater" } },
	{ number = "7559-62742-2", album = { "Six Degrees of Inner Turbulence" }, artist = { "Dream Theater" } },
	{ number = "7559-62891-2", album = { "Train of Thought" }, artist = { "Dream Theater" } },
	{ number = "7567-83793-2", album = { "Octavarium" }, artist = { "Dream Theater" } },
	{ number = "1686-179922", album = { "Systematic Chaos" }, artist = { "Dream Theater" } },
	{ number = "1686-178832", album = { "Black Clouds & Silver Linings" }, artist = { "Dream Theater" } },
	{ number = "RR7765-2", album = { "A Dramatic Turn of Events" }, artist = { "Dream Theater" } },
	{ number = "1686-176042", album = { "Dream Theater" }, artist = { "Dream Theater" } },
	{ number = "1686-174932", album = { "The Astonishing" }, artist = { "Dream Theater" } },
}

